services:
  postgres-test:
    image: postgres:17
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "template1"
    ports:
      - "5433:5432"

  versitygw-test:
    image: versity/versitygw:latest
    environment:
      ROOT_ACCESS_KEY: access
      ROOT_SECRET_KEY: secretsecret
      VGW_BACKEND: posix
      VGW_BACKEND_ARG: /var/lib
    ports:
      - "7072:7070"
