name: Compatibility

on:
  schedule:
    - cron: "14 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: maragudk/workflows/.github/workflows/compatibility.yml@main
    with:
      s3: true
      postgres: true
